<a href="https://colab.research.google.com/github/fahadrajput99/EDA-Using-Pandas/blob/main/email%20spam%20using%20sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('/content/spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [3]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [4]:
df['spam'].shape

(5572,)

In [5]:
df.isnull().sum()

Category    0
Message     0
spam        0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.Message,df.spam,test_size=0.25)

In [7]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_count=cv.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
x_train_count.shape

(4179, 7487)

In [9]:
y_train.shape

(4179,)

In [10]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [11]:
print("1 is spam","0 is ham")

emails={
    "hey fahad can we meet tommorow to see circket match",
    "upto 20% discount to all courses"
}

email_count=cv.transform(emails)
model.predict(email_count)

1 is spam 0 is ham


array([0, 1])

In [12]:
x_test_count=cv.transform(x_test)
model.score(x_test_count,y_test)

0.9885139985642498

In [13]:
#A big code convert into simple lines using sklearn pipeline

In [14]:
from sklearn.pipeline import Pipeline
plt=Pipeline([
    ('vectorizre' , CountVectorizer()),
    ('nb' , MultinomialNB())
])

In [15]:
plt.fit(x_train,y_train)

Pipeline(steps=[('vectorizre', CountVectorizer()), ('nb', MultinomialNB())])

In [16]:
emails={
    "hey fahad can we meet tommorow to see circket match",
    "upto 20% discount to all courses"
}
plt.predict(emails)

array([0, 1])

In [20]:
plt.predict(x_test.head(20))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])