<a href="https://colab.research.google.com/github/fahadrajput99/EDA-Using-Pandas/blob/main/grid_search%20cv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
df=pd.read_csv('/content/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()

In [22]:
df['Species']=la.fit_transform(df['Species'])

In [23]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [24]:
y=df.Species
input=df.drop(['Species'],axis=1,inplace=True)

In [25]:
input

In [28]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [39]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test =train_test_split(df,y,test_size=0.2)

In [52]:
y_test.shape

(30,)

In [47]:
from sklearn.svm import SVC
model = SVC(kernel='linear', C=30, gamma='auto')
model.fit(x_train, y_train)
accuracy = model.score(x_test, y_test)

In [48]:
accuracy

1.0

In [54]:
from sklearn.model_selection import cross_val_score


In [64]:
cross_val_score(SVC(kernel='linear', C=10, gamma='auto'),x_train,y_train,cv=5)

array([1., 1., 1., 1., 1.])

In [63]:
cross_val_score(SVC(kernel='rbf', C=20, gamma='auto'),x_train,y_train,cv=5)

array([1., 1., 1., 1., 1.])

In [62]:
cross_val_score(SVC(kernel='rbf', C=30, gamma='auto'),x_train,y_train,cv=5)

array([1., 1., 1., 1., 1.])

In [65]:
from sklearn.linear_model import LogisticRegression
la=LogisticRegression()
la.fit(x_train,y_train)
accuracy=la.score(x_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [66]:
accuracy

1.0

In [67]:
import numpy as np
kernals=['rbf','linear']
c=[1,10,20]
avg_score={}
for kval in kernals:
  for cval in c:
    cv_score=cross_val_score(SVC(kernel='rbf', C=30, gamma='auto'),x_train,y_train,cv=5)
    avg_score[kval + '_' + str(cval)]=np.average(cv_score)

avg_score

{'rbf_1': 1.0,
 'rbf_10': 1.0,
 'rbf_20': 1.0,
 'linear_1': 1.0,
 'linear_10': 1.0,
 'linear_20': 1.0}

In [68]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameters = {
    'kernel': ['rbf', 'linear'],
    'C': [1, 10, 20],
}

clf = GridSearchCV(SVC(gamma='auto'), parameters, cv=5, return_train_score=False)
clf.fit(x_train, y_train)

# Access the results using 'cv_results_'
results = clf.cv_results_
print(results)


{'mean_fit_time': array([0.00421238, 0.00211172, 0.00315313, 0.00214849, 0.00309429,
       0.00208139]), 'std_fit_time': array([1.74942031e-03, 1.72305224e-05, 4.11475933e-05, 4.07383615e-05,
       2.00887143e-05, 2.05017798e-05]), 'mean_score_time': array([0.00209312, 0.00164948, 0.00187683, 0.00176191, 0.0017797 ,
       0.00161567]), 'std_score_time': array([4.79114658e-04, 1.80472628e-05, 1.59266252e-04, 1.33680853e-04,
       2.33988614e-05, 6.71240400e-06]), 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'C': 1, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}, {'C': 10, 'kernel': 'rbf'}, {'C': 10, 'kernel': 'linear'}, {'C': 20, 'kernel': 'rbf'}, {'C': 20, 

In [69]:
df=pd.DataFrame(results)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.004212      0.001749         0.002093        0.000479       1   
1       0.002112      0.000017         0.001649        0.000018       1   
2       0.003153      0.000041         0.001877        0.000159      10   
3       0.002148      0.000041         0.001762        0.000134      10   
4       0.003094      0.000020         0.001780        0.000023      20   
5       0.002081      0.000021         0.001616        0.000007      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}                1.0   
1       linear   {'C': 1, 'kernel': 'linear'}                1.0   
2          rbf     {'C': 10, 'kernel': 'rbf'}                1.0   
3       linear  {'C': 10, 'kernel': 'linear'}                1.0   
4          rbf     {'C': 20, 'kernel': 'rbf'}                1.0   
5       linear  {'C': 20, 'kernel': 'linear'}                1.0   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0                1.0                1.0                1.0   
1                1.0                1.0                1.0                1.0   
2                1.0                1.0                1.0                1.0   
3                1.0                1.0                1.0                1.0   
4                1.0                1.0                1.0                1.0   
5                1.0                1.0                1.0                1.0   

   mean_test_score  std_test_score  rank_test_score  
0              1.0             0.0                1  
1              1.0             0.0                1  
2              1.0             0.0                1  
3              1.0             0.0                1  
4              1.0             0.0                1  
5              1.0             0.0                1

In [70]:
df[['param_C' , 'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf              1.0
1       1       linear              1.0
2      10          rbf              1.0
3      10       linear              1.0
4      20          rbf              1.0
5      20       linear              1.0

In [71]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [73]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'param': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'param': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'param': {
            'C': [1, 5, 10]
        }
    }
}

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['param'], cv=5, return_train_score=False)
    clf.fit(x_train, y_train)
    print(f"Best parameters for {model_name}: {clf.best_params_}")
    print(f"Best score for {model_name}: {clf.best_score_}\n")

Best parameters for svm: {'C': 1, 'kernel': 'rbf'}
Best score for svm: 1.0

Best parameters for random_forest: {'n_estimators': 10}
Best score for random_forest: 0.9916666666666668

Best parameters for logistic_regression: {'C': 10}
Best score for logistic_regression: 1.0

